<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<TargetFrameworks>net10.0</TargetFrameworks>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationId>com.companyname.mauief.migrator</ApplicationId>

	</PropertyGroup>

	<ItemGroup>

		<!--Local database-->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />

		<!--To be able to create migrations-->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\MauiEF.Shared.csproj" />
	</ItemGroup>

</Project>
