//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purse.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Purse.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a resource for this value or VisualElement.
        /// </summary>
        public static string _DefineResource {
            get {
                return ResourceManager.GetString("_DefineResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd, MMM d, yyyy.
        /// </summary>
        public static string AbbreviatedDatePattern {
            get {
                return ResourceManager.GetString("AbbreviatedDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add words to Filter.
        /// </summary>
        public static string AddFilterWords {
            get {
                return ResourceManager.GetString("AddFilterWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to create one..
        /// </summary>
        public static string AddHint {
            get {
                return ResourceManager.GetString("AddHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Income Source.
        /// </summary>
        public static string AddIncomeSource {
            get {
                return ResourceManager.GetString("AddIncomeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?? Add Manually.
        /// </summary>
        public static string AddManuallyBtn {
            get {
                return ResourceManager.GetString("AddManuallyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Income Source.
        /// </summary>
        public static string AddNewIncomeSource {
            get {
                return ResourceManager.GetString("AddNewIncomeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Task.
        /// </summary>
        public static string AddNewTask {
            get {
                return ResourceManager.GetString("AddNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Vendor.
        /// </summary>
        public static string AddNewVendor {
            get {
                return ResourceManager.GetString("AddNewVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Split.
        /// </summary>
        public static string AddSplit {
            get {
                return ResourceManager.GetString("AddSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor.
        /// </summary>
        public static string AddVendor {
            get {
                return ResourceManager.GetString("AddVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetic Code.
        /// </summary>
        public static string AlphabeticCode {
            get {
                return ResourceManager.GetString("AlphabeticCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purse.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assigned items.
        /// </summary>
        public static string AssignedItemsCount {
            get {
                return ResourceManager.GetString("AssignedItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Work items.
        /// </summary>
        public static string AssignedWorkItems {
            get {
                return ResourceManager.GetString("AssignedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate to access Hour Tracker.
        /// </summary>
        public static string AuthenticationRequestMessage {
            get {
                return ResourceManager.GetString("AuthenticationRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock {0}.
        /// </summary>
        public static string AuthenticationTitle {
            get {
                return ResourceManager.GetString("AuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Denied.
        /// </summary>
        public static string AuthorizationDenied {
            get {
                return ResourceManager.GetString("AuthorizationDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This category cannot be deleted because it is currently used in {0} transaction(s)..
        /// </summary>
        public static string CannotDeleteCategoryMessageFormat {
            get {
                return ResourceManager.GetString("CannotDeleteCategoryMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Category.
        /// </summary>
        public static string CannotDeleteCategoryTitle {
            get {
                return ResourceManager.GetString("CannotDeleteCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Detail.
        /// </summary>
        public static string CategoryDetail {
            get {
                return ResourceManager.GetString("CategoryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change pin.
        /// </summary>
        public static string ChangePin {
            get {
                return ResourceManager.GetString("ChangePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color.
        /// </summary>
        public static string ChooseColor {
            get {
                return ResourceManager.GetString("ChooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults to the most used item name.
        /// </summary>
        public static string ComboBoxDefault {
            get {
                return ResourceManager.GetString("ComboBoxDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Gallery.
        /// </summary>
        public static string ControlGallery {
            get {
                return ResourceManager.GetString("ControlGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Expense Category.
        /// </summary>
        public static string CreateExpenseCategory {
            get {
                return ResourceManager.GetString("CreateExpenseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Income Category.
        /// </summary>
        public static string CreateIncomeCategory {
            get {
                return ResourceManager.GetString("CreateIncomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.dd, dddd.
        /// </summary>
        public static string CustomListDatePattern {
            get {
                return ResourceManager.GetString("CustomListDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data created.
        /// </summary>
        public static string DataCreated {
            get {
                return ResourceManager.GetString("DataCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test data successfully created..
        /// </summary>
        public static string DataCreatedMessage {
            get {
                return ResourceManager.GetString("DataCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as default item.
        /// </summary>
        public static string DefaultItem {
            get {
                return ResourceManager.GetString("DefaultItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the category &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteCategoryMessageFormat {
            get {
                return ResourceManager.GetString("DeleteCategoryMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string DeleteCategoryTitle {
            get {
                return ResourceManager.GetString("DeleteCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete all selected items.
        /// </summary>
        public static string DeleteConfirmAll {
            get {
                return ResourceManager.GetString("DeleteConfirmAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard and Leave.
        /// </summary>
        public static string DiscardAndLeaveButton {
            get {
                return ResourceManager.GetString("DiscardAndLeaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to € Amount.
        /// </summary>
        public static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a category name.
        /// </summary>
        public static string EnterCategoryName {
            get {
                return ResourceManager.GetString("EnterCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City.
        /// </summary>
        public static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description (Optional).
        /// </summary>
        public static string EnterDescriptionOptional {
            get {
                return ResourceManager.GetString("EnterDescriptionOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Income Source Name.
        /// </summary>
        public static string EnterIncomeSourceName {
            get {
                return ResourceManager.GetString("EnterIncomeSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Pin Code.
        /// </summary>
        public static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to € Planned Amount.
        /// </summary>
        public static string EnterPlannedAmount {
            get {
                return ResourceManager.GetString("EnterPlannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Postal Code.
        /// </summary>
        public static string EnterPostalCode {
            get {
                return ResourceManager.GetString("EnterPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter State/Province.
        /// </summary>
        public static string EnterStateOrProvince {
            get {
                return ResourceManager.GetString("EnterStateOrProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Street Address.
        /// </summary>
        public static string EnterStreetAddress {
            get {
                return ResourceManager.GetString("EnterStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vendor Description (Optional).
        /// </summary>
        public static string EnterVendorDescription {
            get {
                return ResourceManager.GetString("EnterVendorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vendor Name.
        /// </summary>
        public static string EnterVendorName {
            get {
                return ResourceManager.GetString("EnterVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) occurred.
        /// </summary>
        public static string ErrorsOccurred {
            get {
                return ResourceManager.GetString("ErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From time.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM d, yyyy HH:mm:ss tt.
        /// </summary>
        public static string FullDateTimePattern {
            get {
                return ResourceManager.GetString("FullDateTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open summary:.
        /// </summary>
        public static string GroupHeaderOpenTitle {
            get {
                return ResourceManager.GetString("GroupHeaderOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open hours:.
        /// </summary>
        public static string GroupHeaderOpenWorkingHoursTitle {
            get {
                return ResourceManager.GetString("GroupHeaderOpenWorkingHoursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid summary:.
        /// </summary>
        public static string GroupHeaderPaidTitle {
            get {
                return ResourceManager.GetString("GroupHeaderPaidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid hours:.
        /// </summary>
        public static string GroupHeaderPaidWorkingHoursTitle {
            get {
                return ResourceManager.GetString("GroupHeaderPaidWorkingHoursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        public static string GroupHeaderSummaryText {
            get {
                return ResourceManager.GetString("GroupHeaderSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate.
        /// </summary>
        public static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Source Detail.
        /// </summary>
        public static string IncomeSourceDetail {
            get {
                return ResourceManager.GetString("IncomeSourceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Sources.
        /// </summary>
        public static string IncomeSources {
            get {
                return ResourceManager.GetString("IncomeSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Default.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is income Category.
        /// </summary>
        public static string IsIncome {
            get {
                return ResourceManager.GetString("IsIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Model Type.
        /// </summary>
        public static string ItemModelType {
            get {
                return ResourceManager.GetString("ItemModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM d, yyyy.
        /// </summary>
        public static string LongDatePattern {
            get {
                return ResourceManager.GetString("LongDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm:ss.
        /// </summary>
        public static string LongTimePattern {
            get {
                return ResourceManager.GetString("LongTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Unit.
        /// </summary>
        public static string MinorUnit {
            get {
                return ResourceManager.GetString("MinorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No income sources found..
        /// </summary>
        public static string NoIncomeSourcesFound {
            get {
                return ResourceManager.GetString("NoIncomeSourcesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items added yet..
        /// </summary>
        public static string NoItemsAdded {
            get {
                return ResourceManager.GetString("NoItemsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions yet..
        /// </summary>
        public static string NoTransactions {
            get {
                return ResourceManager.GetString("NoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vendors found..
        /// </summary>
        public static string NoVendorsFound {
            get {
                return ResourceManager.GetString("NoVendorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number to Basic.
        /// </summary>
        public static string NumberToBasic {
            get {
                return ResourceManager.GetString("NumberToBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Code.
        /// </summary>
        public static string NumericCode {
            get {
                return ResourceManager.GetString("NumericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open:.
        /// </summary>
        public static string OpenWithColon {
            get {
                return ResourceManager.GetString("OpenWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have errors on the Page. Would you like to stay on the page and correct the errors, or just simply discard your changes?.
        /// </summary>
        public static string PageErrorMessage {
            get {
                return ResourceManager.GetString("PageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaidXXX.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment state.
        /// </summary>
        public static string PaymentState {
            get {
                return ResourceManager.GetString("PaymentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMMM yyyy.
        /// </summary>
        public static string PickerDateFormatLong {
            get {
                return ResourceManager.GetString("PickerDateFormatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string PickerDateFormatShort {
            get {
                return ResourceManager.GetString("PickerDateFormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between a minimum of {1} and a maximum of {2}..
        /// </summary>
        public static string RangeErrorMessage {
            get {
                return ResourceManager.GetString("RangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt details.
        /// </summary>
        public static string ReceiptDetails {
            get {
                return ResourceManager.GetString("ReceiptDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate Sample Data?.
        /// </summary>
        public static string RecreateSampleData {
            get {
                return ResourceManager.GetString("RecreateSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will overwrite all existing data. Would you like to proceed?.
        /// </summary>
        public static string RecreateSampleDataMessage {
            get {
                return ResourceManager.GetString("RecreateSampleDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?? Scan Receipt.
        /// </summary>
        public static string ScanReceiptBtn {
            get {
                return ResourceManager.GetString("ScanReceiptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this category as the preferred default selection.
        /// </summary>
        public static string SetPreferredDefault {
            get {
                return ResourceManager.GetString("SetPreferredDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M/d/yyyy.
        /// </summary>
        public static string ShortDatePattern {
            get {
                return ResourceManager.GetString("ShortDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh\:mm.
        /// </summary>
        public static string ShortTimePattern {
            get {
                return ResourceManager.GetString("ShortTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string SortableDatePattern {
            get {
                return ResourceManager.GetString("SortableDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        public static string SortableDateTimePattern {
            get {
                return ResourceManager.GetString("SortableDateTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay and Fix.
        /// </summary>
        public static string StayAndFixButton {
            get {
                return ResourceManager.GetString("StayAndFixButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a pre-defined system category. Its name and type cannot be modified or deleted, but you can set it as your preferred default category..
        /// </summary>
        public static string SystemCategoryDescription {
            get {
                return ResourceManager.GetString("SystemCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TaskItemCollection {
            get {
                return ResourceManager.GetString("TaskItemCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskItemDetail {
            get {
                return ResourceManager.GetString("TaskItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ThroughDate {
            get {
                return ResourceManager.GetString("ThroughDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To time.
        /// </summary>
        public static string ThroughTime {
            get {
                return ResourceManager.GetString("ThroughTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is: {0:HH}:{0:mm}:{0:ss}.
        /// </summary>
        public static string TimeIs {
            get {
                return ResourceManager.GetString("TimeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is: {0:c}.
        /// </summary>
        public static string TimeIs2 {
            get {
                return ResourceManager.GetString("TimeIs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle on if this category represents Income (e.g. Salary).
        /// </summary>
        public static string ToggleIncomeCategory {
            get {
                return ResourceManager.GetString("ToggleIncomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transactions.
        /// </summary>
        public static string TransactionCountFormat {
            get {
                return ResourceManager.GetString("TransactionCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Detail.
        /// </summary>
        public static string TransactionDetail {
            get {
                return ResourceManager.GetString("TransactionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        public static string TransactionHistory {
            get {
                return ResourceManager.GetString("TransactionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Split.
        /// </summary>
        public static string TransactionSplit {
            get {
                return ResourceManager.GetString("TransactionSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are validation errors on this page. Would you like to stay and fix them, or discard changes and leave?.
        /// </summary>
        public static string UnsavedChangesErrorsMessage {
            get {
                return ResourceManager.GetString("UnsavedChangesErrorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all.
        /// </summary>
        public static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?? Upload Receipt.
        /// </summary>
        public static string UploadReceiptBtn {
            get {
                return ResourceManager.GetString("UploadReceiptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Detail.
        /// </summary>
        public static string VendorDetail {
            get {
                return ResourceManager.GetString("VendorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningOccured {
            get {
                return ResourceManager.GetString("WarningOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time.
        /// </summary>
        public static string WorkingTime {
            get {
                return ResourceManager.GetString("WorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time overview.
        /// </summary>
        public static string WorkingTimeCollection {
            get {
                return ResourceManager.GetString("WorkingTimeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time detail.
        /// </summary>
        public static string WorkingTimeDetail {
            get {
                return ResourceManager.GetString("WorkingTimeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter some Text to get a list of all given names for Workitems before.
        /// </summary>
        public static string WorkItemAutoCompleteViewPlaceholder {
            get {
                return ResourceManager.GetString("WorkItemAutoCompleteViewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No work items found for your input.
        /// </summary>
        public static string WorkItemNoResultsFoundText {
            get {
                return ResourceManager.GetString("WorkItemNoResultsFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplaces.
        /// </summary>
        public static string WorkplaceCollection {
            get {
                return ResourceManager.GetString("WorkplaceCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        public static string WorkplaceDetail {
            get {
                return ResourceManager.GetString("WorkplaceDetail", resourceCulture);
            }
        }        public static string CreateNewVendor {
            get {
                return ResourceManager.GetString("CreateNewVendor", resourceCulture);
            }
        }
        public static string EditSelectedVendor {
            get {
                return ResourceManager.GetString("EditSelectedVendor", resourceCulture);
            }
        }
        public static string EditSelectedCategory {
            get {
                return ResourceManager.GetString("EditSelectedCategory", resourceCulture);
            }
        }
        public static string SelectVendor {
            get {
                return ResourceManager.GetString("SelectVendor", resourceCulture);
            }
        }
    }
}
