//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purse.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormatResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Purse.Resources.Strings.FormatResources", typeof(FormatResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a resource for this value or VisualElement (FormatResources).
        /// </summary>
        public static string _DefineResource {
            get {
                return ResourceManager.GetString("_DefineResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd, MMM d, yyyy.
        /// </summary>
        public static string AbbreviatedDatePattern {
            get {
                return ResourceManager.GetString("AbbreviatedDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM d, yyyy HH:mm:ss tt.
        /// </summary>
        public static string FullDateTimePattern {
            get {
                return ResourceManager.GetString("FullDateTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM d, yyyy.
        /// </summary>
        public static string LongDatePattern {
            get {
                return ResourceManager.GetString("LongDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm:ss.
        /// </summary>
        public static string LongTimePattern {
            get {
                return ResourceManager.GetString("LongTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMMM yyyy.
        /// </summary>
        public static string PickerDateFormatLong {
            get {
                return ResourceManager.GetString("PickerDateFormatLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string PickerDateFormatShort {
            get {
                return ResourceManager.GetString("PickerDateFormatShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M/d/yyyy.
        /// </summary>
        public static string ShortDatePattern {
            get {
                return ResourceManager.GetString("ShortDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hh\:mm.
        /// </summary>
        public static string ShortTimePattern {
            get {
                return ResourceManager.GetString("ShortTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string SortableDatePattern {
            get {
                return ResourceManager.GetString("SortableDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.
        /// </summary>
        public static string SortableDateTimePattern {
            get {
                return ResourceManager.GetString("SortableDateTimePattern", resourceCulture);
            }
        }
    }
}
