//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purse.Shared.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExpenseCategories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpenseCategories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Purse.Shared.Resources.Strings.ExpenseCategories", typeof(ExpenseCategories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leisure &amp; Entertainment.
        /// </summary>
        public static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp; Groceries.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare &amp; Medical.
        /// </summary>
        public static string Healthcare {
            get {
                return ResourceManager.GetString("Healthcare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing &amp; Rent.
        /// </summary>
        public static string Housing {
            get {
                return ResourceManager.GetString("Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Expense.
        /// </summary>
        public static string OtherExpense {
            get {
                return ResourceManager.GetString("OtherExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping &amp; Clothes.
        /// </summary>
        public static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation &amp; Gas.
        /// </summary>
        public static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities (Electricity, Water, Internet).
        /// </summary>
        public static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
    }
}
